name: Inject Cache
description: "Injects the cached data into the docker build(x|kit) process"
inputs:
  cache-source:
    default: cache
    description: "Where the cache is stored in the calling workspace. Default: `cache`"
  scratch-dir:
    default: scratch
    description: "Where the action is stores some temporary files for its processing. Default: `scratch`"
runs:
  using: composite
  steps:
    - name: Clean Directories
      shell: bash
      run: |
        rm -Rf ${{ inputs.scratch-dir }} && mkdir -p ${{ inputs.scratch-dir }} ${{ inputs.cache-source }}
    - name: Prepare Timestamp for Layer Cache Busting
      shell: bash
      run: |
        date --iso=ns | tee ${{ inputs.scratch-dir }}/buildstamp
    - name: Prepare Dancefile to Access Caches
      shell: bash
      run: |
        cat > ${{ inputs.scratch-dir }}/Dancefile.inject <<EOF
        FROM alpine:3.17
        COPY ${{ inputs.scratch-dir }}/buildstamp buildstamp
        RUN --mount=type=cache,target=/root/.cache/go-build \
            --mount=type=cache,target=/go/pkg \
            --mount=type=bind,source=${{ inputs.cache-source }},target=/var/dance-cache \
            cp -R /var/dance-cache/go-build /root/.cache/go-build \
            && cp -R /var/dance-cache/pkg /go/pkg || true
        EOF
        cat ${{ inputs.scratch-dir }}/Dancefile.inject
    - name: Inject Data into Docker Cache
      shell: bash
      run: |
        docker buildx build -f ${{ inputs.scratch-dir }}/Dancefile.inject --tag dance:inject .
